version: "3.8"

# add service to postgres and go
services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  go:
    container_name: go-social
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb