// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExpressionFilter struct {
	Expression *Filters `json:"expression"`
}

type Filters struct {
	Field *string `json:"field"`
	Like  *string `json:"like"`
	Gte   *string `json:"gte"`
	Lte   *string `json:"lte"`
}

type User struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Year    int     `json:"year"`
	Friends []*User `json:"friends"`
}

type UserFilter struct {
	And []*ExpressionFilter `json:"and"`
}
